---
clone:
  git:
    image: woodpeckerci/plugin-git@sha256:ebde4a4d07e0e24b630082484d192890dd4f6d442d90bf5466f0763860f83652
    settings:
      skip-verify: true

when:
  - branch: master
    event: [push, manual]

steps:
  - name: Build
    image: codeberg.org/woodpecker-plugins/node-pm@sha256:bff3ee2d7492e89a0dfbe6ee4c7d5ce636108cd973c0c355269f681e8dd8a196
    settings:
      run: build
      frozen_lockfile: true

  - name: Deploy to OVHcloud S3
    image: amazon/aws-cli:latest@sha256:4de7e0404fb6b5b9cabd39c965973cfd27ace98a9ab8b555cae8db5cb4643b42
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: OVH_S3_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: OVH_S3_SECRET_KEY
      AWS_DEFAULT_REGION: rbx
    commands:
      - aws s3 sync dist/ s3://erwanleboucher.dev --delete --acl public-read --endpoint-url https://s3.rbx.io.cloud.ovh.net
