---
clone:
  git:
    image: woodpeckerci/plugin-git@sha256:e6326a142d9bf08c6cc79cee3b3b26c87c15c999f89fb0b14c98d6031639968a
    settings:
      skip-verify: true

when:
  - branch: master
    event: [push, manual]

steps:
  - name: Type check
    image: codeberg.org/woodpecker-plugins/node-pm@sha256:bff3ee2d7492e89a0dfbe6ee4c7d5ce636108cd973c0c355269f681e8dd8a196
    settings:
      run: type-check
      frozen_lockfile: true
      ignore_node_modules: true

  - name: Build
    image: codeberg.org/woodpecker-plugins/node-pm@sha256:bff3ee2d7492e89a0dfbe6ee4c7d5ce636108cd973c0c355269f681e8dd8a196
    settings:
      run: build-only
      frozen_lockfile: true

  - name: Deploy to OVHcloud S3
    image: amazon/aws-cli:latest@sha256:96516991f34382a7667f3e59db2262f209a86ab4ea371e22242f0898a4e9ffc8
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: OVH_S3_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: OVH_S3_SECRET_KEY
      AWS_DEFAULT_REGION: rbx
    commands:
      - aws s3 sync dist/ s3://erwanleboucher.dev --delete --acl public-read --endpoint-url https://s3.rbx.io.cloud.ovh.net
