---
clone:
  git:
    image: woodpeckerci/plugin-git
    settings:
      skip-verify: true

when:
  - branch: master
    event: [push, manual]

steps:
  - name: Type check
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: type-check
      frozen_lockfile: true
      ignore_node_modules: true

  - name: Build
    image: codeberg.org/woodpecker-plugins/node-pm
    settings:
      run: build-only
      frozen_lockfile: true

  - name: Deploy to OVHcloud S3
    image: amazon/aws-cli:latest
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: OVH_S3_ACCESS_KEY
      AWS_SECRET_ACCESS_KEY:
        from_secret: OVH_S3_SECRET_KEY
      AWS_DEFAULT_REGION: rbx
    commands:
      - aws s3 sync dist/ s3://erwanleboucher.dev --delete --acl public-read --endpoint-url https://s3.rbx.io.cloud.ovh.net
